version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
  - "@jenkinsci/caffeine-api-plugin-developers"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
