version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    # Version 3 and higher required Java 11, so ignore those
    - dependency-name: "express"
      versions: [ "[3.0.0)" ]
  reviewers:
  - "@jenkinsci/caffeine-api-plugin-developers"
