version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    # Version 3 and higher required Java 11, so ignore those
    - dependency-name: "com.github.ben-manes.caffeine:caffeine"
      versions: [ "[3.0.0,)" ]
  reviewers:
  - "@jenkinsci/caffeine-api-plugin-developers"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
